const { ENPOINTS } = require("./endpoints");

exports.Mapel = [
  {
    id: 1,
    inisial: "PU",
    time: 1800,
    jumlah: 30,
    picture: "./general_reasoning.jpg",
    mapel: "Penalaran Umum",
  },
  {
    id: 2,
    inisial: "PM",
    time: 1800,
    jumlah: 20,
    picture: "./math_reasoning.jpg",
    mapel: "Penalaran Matematika",
  },
  {
    id: 3,
    inisial: "PK",
    time: 1200,
    jumlah: 15,
    mapel: "Pengetahuan Kuantitatif",
    picture: "./quantitative_knowledge.jpg",
  },
  {
    id: 4,
    inisial: "PPU",
    time: 900,
    jumlah: 20,
    picture: "./general_knowledge.jpg",
    mapel: "Pengetahuan dan Pemahaman Umum",
  },
  {
    id: 5,
    inisial: "PBM",
    time: 1500,
    jumlah: 20,
    mapel: "Pemahaman Bacaan dan Menulis",
    picture: "./reading_and_writing_knowledge.jpg",
  },
  {
    id: 6,
    inisial: "LBIND",
    time: 2700,
    jumlah: 30,
    picture: "./language.jpg",
    mapel: "Literasi Bahasa Indonesia",
  },
  {
    id: 7,
    inisial: "LBING",
    time: 1800,
    jumlah: 20,
    picture: "./language.jpg",
    mapel: "Literasi Bahasa Inggris",
  },
];
